// Generated by CoffeeScript 1.7.1
(function() {
  var Button, Calculator, DigitButton,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Calculator = (function() {
    Calculator.digits = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];

    Calculator.operators = ['+', '-', '='];

    function Calculator(element) {
      this.element = element;
      this.build_buttons();
    }

    Calculator.prototype.build_buttons = function() {
      this.constructor.digits.forEach((function(_this) {
        return function(number) {
          return _this.addButton(new DigitButton(number));
        };
      })(this));
      return this.operators;
    };

    Calculator.prototype.addButton = function(button) {
      return this.element.querySelector('buttons').appendChild(button.element);
    };

    return Calculator;

  })();

  Button = (function() {
    function Button(text) {
      this.element = document.createElement('button');
      this.element.textContent = text;
      this.element.addEventListener('click', (function(_this) {
        return function() {
          return _this.action();
        };
      })(this));
    }

    return Button;

  })();

  DigitButton = (function(_super) {
    __extends(DigitButton, _super);

    function DigitButton() {
      return DigitButton.__super__.constructor.apply(this, arguments);
    }

    DigitButton.prototype.action = function() {
      return window.calculator.addDgitToCurrentOperant(this.digit);
    };

    return DigitButton;

  })(Button);

  window.calculator = new Calculator(document.querySelector('calculator'));

}).call(this);
